
----------------------------------######## DDL #################--------------------------------


======>>> dim_consumers:


CREATE TABLE 
    dim_consumers 
    ( 
        consumer_key 		  BIGINT NOT NULL, 
        consumer_id 		  CHARACTER VARYING(100) NOT NULL ENCODE ZSTD, 
        report_licensor 	  CHARACTER VARYING(3) NOT NULL ENCODE ZSTD,
		created_at            TIMESTAMP not null default sysdate ENCODE az64
	) 
    DISTSTYLE EVEN 
    SORTKEY 
    ( 
        consumer_key 
    );
ALTER TABLE appleitunes.dim_consumers OWNER TO etl_it;
ALTER TABLE appleitunes.dim_consumers ADD CONSTRAINT dim_consumers_pk PRIMARY KEY (consumer_key);




======>>> dim_partner_info:


CREATE TABLE 
    dim_partner_info 
    ( 
        partner_info_key   BIGINT NOT NULL, 
        apple_id           BIGINT NOT NULL ENCODE AZ64, 
		upc                CHARACTER VARYING(100) NOT NULL ENCODE ZSTD,
        isrc               CHARACTER VARYING(100) NOT NULL ENCODE ZSTD, 
        artist_name        CHARACTER VARYING(2000) ENCODE ZSTD,
		track_title        CHARACTER VARYING(1000) ENCODE ZSTD,
		label_name         CHARACTER VARYING(1000) ENCODE ZSTD,
		product_identifier CHARACTER VARYING(5) ENCODE ZSTD,
        isan               CHARACTER VARYING(100) ENCODE ZSTD, 
		asset_content      CHARACTER VARYING(100) ENCODE ZSTD, 
        grid               CHARACTER VARYING(100) ENCODE ZSTD, 
		provider_genre     CHARACTER VARYING(100) ENCODE ZSTD, 
		prod_no_dig        CHARACTER VARYING(20) ENCODE ZSTD,
        created_at         TIMESTAMP not null default sysdate ENCODE az64
    ) 
    DISTSTYLE EVEN 
    SORTKEY SORTKEY 
    ( 
        partner_info_key,
        isrc 
    );
ALTER TABLE appleitunes.dim_partner_info OWNER TO etl_it;
ALTER TABLE appleitunes.dim_partner_info ADD CONSTRAINT dim_partner_info_pk PRIMARY KEY (partner_info_key);




======>>>> dim_partner_regions:


CREATE TABLE 
    dim_partner_regions 
    ( 
        partner_region_key  BIGINT NOT NULL, 
        country_code        CHARACTER VARYING(2) ENCODE ZSTD, 
        zip_code            CHARACTER VARYING(10) ENCODE ZSTD, 
        etl_hash            CHARACTER VARYING(1000) ENCODE ZSTD, 
        created_at          TIMESTAMP not null default sysdate ENCODE az64
    ) 
    DISTSTYLE EVEN 
    SORTKEY 
    ( 
        partner_region_key 
    );
ALTER TABLE appleitunes.dim_partner_regions OWNER TO etl_it;
ALTER TABLE appleitunes.dim_partner_regions ADD CONSTRAINT dim_partner_regions_pk PRIMARY KEY (partner_region_key);





======>>> dim_promo_info:


CREATE TABLE 
    dim_promo_info 
    ( 
        promo_info_key        BIGINT NOT NULL, 
        promo_code            CHARACTER VARYING(100) NOT NULL ENCODE ZSTD, 
        cma_code              CHARACTER VARYING(100) NOT NULL ENCODE ZSTD, 
        created_at            TIMESTAMP not null default sysdate ENCODE az64
    ) 
    DISTSTYLE EVEN 
    SORTKEY  
    ( 
        promo_info_key 
    );
ALTER TABLE appleitunes.dim_promo_info OWNER TO etl_it;
ALTER TABLE appleitunes.dim_promo_info ADD CONSTRAINT dim_promo_info_pk PRIMARY KEY (promo_info_key);





======>>> fact_streams:


CREATE TABLE 
    fact_streams 
    ( 
        fact_key         		  BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY IDENTITY ENCODE AZ64,
		report_date               DATE NOT NULL,
		download_date             DATE NOT NULL,
		consumer_key              BIGINT NOT NULL ENCODE AZ64,
		country_code              CHARACTER VARYING(2) NOT NULL ENCODE ZSTD, 
		artist_key                BIGINT NOT NULL ENCODE AZ64,
		product_key               BIGINT NOT NULL ENCODE AZ64,
		label_key                 BIGINT NOT NULL ENCODE AZ64,
		dst_key                   BIGINT NOT NULL ENCODE AZ64,
		ppv_key                   BIGINT NOT NULL ENCODE AZ64,
		spnl_key                  BIGINT NOT NULL ENCODE AZ64,
		sales_type_key            BIGINT NOT NULL ENCODE AZ64,
		sales_category_key        CHARACTER VARYING(100) ENCODE ZSTD,
		sales_division_key        BIGINT NOT NULL ENCODE AZ64,
		partner_info_key          BIGINT NOT NULL ENCODE AZ64,
		partner_region_key        BIGINT NOT NULL ENCODE AZ64,
        promo_info_key		      BIGINT NOT NULL ENCODE AZ64,
		royalty_currency_key      CHARACTER VARYING(10) ENCODE ZSTD,
		consumer_currency_key     CHARACTER VARYING(10) ENCODE ZSTD,
		retail_price			  FLOAT,
		order_id                  INTEGER NOT NULL ENCODE AZ64, 
		preorder_code             CHARACTER VARYING(2) NOT NULL ENCODE ZSTD,
		transaction_amount        FLOAT,
		transaction_code 	      CHARACTER VARYING(10) ENCODE ZSTD,
		transaction_qty			  INTEGER NOT NULL ENCODE AZ64,
		created_at                TIMESTAMP not null default sysdate ENCODE az64
        PRIMARY KEY (fact_key)
		) 
    DISTSTYLE EVEN 
    SORTKEY
    ( 
        report_date 
    );
ALTER TABLE appleitunes.fact_streams OWNER TO etl_it;
ALTER TABLE appleitunes.fact_streams ADD CONSTRAINT fact_streams_pk PRIMARY KEY (fact_key);
ALTER TABLE appleitunes.fact_streams ADD CONSTRAINT fact_streams_fk01 FOREIGN KEY (country_code) REFERENCES common.dim_countries (country_code);
ALTER TABLE appleitunes.fact_streams ADD CONSTRAINT fact_streams_fk02 FOREIGN KEY (label_key) REFERENCES common.dim_labels (label_key);
ALTER TABLE appleitunes.fact_streams ADD CONSTRAINT fact_streams_fk03 FOREIGN KEY (ppv_key) REFERENCES common.dim_ppv (ppv_key);
ALTER TABLE appleitunes.fact_streams ADD CONSTRAINT fact_streams_fk04 FOREIGN KEY (product_key) REFERENCES common.dim_products (product_key);
ALTER TABLE appleitunes.fact_streams ADD CONSTRAINT fact_streams_fk05 FOREIGN KEY (spnl_key) REFERENCES common.dim_spnl_keys (spnl_key);
ALTER TABLE appleitunes.fact_streams ADD CONSTRAINT fact_streams_fk11 FOREIGN KEY (dim_consumers) REFERENCES appleitunes.dim_consumers (consumer_key);
ALTER TABLE appleitunes.fact_streams ADD CONSTRAINT fact_streams_fk12 FOREIGN KEY (dim_partner_info) REFERENCES appleitunes.dim_partner_info (partner_region_key);
ALTER TABLE appleitunes.fact_streams ADD CONSTRAINT fact_streams_fk13 FOREIGN KEY (subscription_type_key) REFERENCES appleitunes.dim_partner_regions (partner_region_key);

